#!/usr/bin/bash
#SBATCH -N 1
#SBATCH --ntasks-per-node=20
#SBATCH -t 2:00:00
#SBATCH -J tunnel
#SBATCH --gres=gpu:K80:1
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
## get tunneling info
XDG_RUNTIME_DIR=""
ipnport=$(shuf -i8000-9999 -n1)
ipnip=$(hostname -i)


## print tunneling instructions to jupyter-log
## start an ipcluster instance and launch jupyter server
module load anaconda3 
conda create -n torch_env -y pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime
eval $(conda shell.bash hook)
##conda init bash
source activate torch_env
